### ISSUE TITLE
Autoscrolling of left joystick through menu options - RE2

### ISSUE THREAD

**Issue by jmvizzle** [praydog/REFramework#105]
I'm using an Index headset and controllers.  When I am in any of the menus, without pressing anything it is just scrolling through all the options like I am holding up or down on the joystick.  I can get it to stop if I put the joystick in just the right place, but it is not really useable.

**Comment by Hypnosphi** [comment]
Same problem with Quest 2 & Oculus Link

**Comment by teddyRbear** [comment]
Same issue on my Quest 2 via Air Link.

**Comment by uGGuUggU** [comment]
I have the same problem - using Index controllers.

**Comment by praydog** [comment]
I'll add an option to set the joystick deadzone.

**Comment by praydog** [comment]
Fixed in 044662fae3308108eb169c13896d5a61c226b846

Find the slider under "VR" in the menu if the default setting doesn't work for you.

**Comment by jmvizzle** [comment]
So the issue is still very intermittent.  Sometimes the game will run for a while from the start with no issue, but seems to inevitably happen at some point.

Once the issue happens though, I have been unable to use the deadzone slider to resolve the issue after dinking with it for a while.  I'm not much of a tech guy though, is there a procedure for dialing that slider in that I should use?

**Comment by Hypnosphi** [comment]
I started experiencing this again, even with the maximum dead zone setting

**Comment by Hypnosphi** [comment]
OK, the case is solved: It only happens when I have a racing wheel connected, disconnecting it completely fixes the issue for me. @jmvizzle @uGGuUggU @teddyRbear you may want to check whether this is the case for you as well
