### ISSUE TITLE
Resident Evil 2 & 3 VR MOD problems with HP Reverb G2 no picture in the headset

### ISSUE THREAD

**Issue by DigginsD** [praydog/REFramework#158]
Hello everyone, I have the following problem, I just don't get a picture in the headset, but the sound is there. The installation is child's play and I know my way around the headset very well, otherwise I get everything up and running, but I lack the approach here, does anyone currently have the same problem?

My Specs:

be quiet! Pure Base 500DX-Ryzen7 3700X-MSI B450 Tomahawk Max-Gigabyte RTX 3080 GamingOC-G.Skill Aegis 3000-Thermaltake Smart RGB 700-HP Reverb G2

**Comment by TechTrooper** [comment]
Works for me. Initially I had to start the game and disable the HDR prompt before it started working.

**Comment by DigginsD** [comment]
No, I don't have an HDR monitor, I've tried all possible solutions. I am surprised that I am the only one with the problem, sooner or later everything will work normally with the headset. I've had the headset since January 21

**Comment by lkberserker** [comment]
Same problem when I play MHR demo, but I'm using PIMAX8K with graphics card 6900xt. Nothing shows in HMD. But a double picture will flicker on my computer screen. I don't have HDR.

**Comment by DigginsD** [comment]
Hello folks...
I still have the same problem, could anyone find a solution so far?
@ikberseker is it working for you now?

**Comment by takesword** [comment]
Try to use the MOD Menu in Game with ur Hand on the Gun to bring VR first person or change some Mod Settings. I got this Problem when i put off my VR and changed it on my screen with my Mouse. I fixed it by clicking out of the Game window after changing with Mouse. For some Reason if you stil focus in Game with ur Mouse u getting very much laggs or Blackscreen. If you change something, minimize the Mod Menu and dont click again into the Game Screen or try to just press WIN Key or CTRL+ESC . After that put on ur VR and this should fix it.

**Comment by DigginsD** [comment]
Still the same problem... Virtual desktop method didn't work either, I'm desperate, I can hear the music menu in the headset but still have no picture.

**Comment by takesword** [comment]
Try to turn off HDR
Load the last dxinput (https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts) to avoid HDR backbuffer
deactivate hardware accelerated gpu scheduling
Try to open in DX11

**Comment by takesword** [comment]
You can also try "Nvidia Control Panel"

-> Resolution -> use "Nvivia Color"

32 bit, 8bpc, ycbcr444, limited

**Comment by takesword** [comment]
Try all the steps and if its stil not working, upload the "re2_framework_log" here.

You can find it in any RE folder and upload it by drag &drop in the comment section here

**Comment by DigginsD** [comment]
Still not working
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7944750/re2_framework_log.txt)
