### ISSUE TITLE
Insert key doesn't open the menu

### ISSUE THREAD

**Issue by J-Silver-J** [praydog/REFramework#609]
"Insert" key doesn't open the menu in RE8, even though I've done everything according to the Installation guide in the description [here](https://www.nexusmods.com/residentevilvillage/mods/60?tab=description). And re2_fw_config.txt doesn't appear either. Please help.

Log: [https://drive.google.com/file/d/1yngTAiSg7Wbg65aYFqD4dOiMrJOiTXm1/view?usp=share_link](https://drive.google.com/file/d/1yngTAiSg7Wbg65aYFqD4dOiMrJOiTXm1/view?usp=share_link)

**Comment by praydog** [comment]
Most likely fixed in 8c34b024d1b2a9bfe51ee3a513a960e8c4b9abe6

**Comment by J-Silver-J** [comment]
I re-downloaded the dinput8.dll today, but still the same issue
